FROM node:18-slim

# تثبيت جميع المكتبات والاعتماديات الأساسية لتشغيل الكروم في بيئة صامتة لـ Linux
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    xdg-utils \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./

# تثبيت الحزم والمكتبات المذكورة في package.json
RUN npm install

# حسم المشكلة: إجبار السيرفر على تحميل كروم المتوافق يدويًا أثناء الـ Build
RUN npx puppeteer browsers install chrome

COPY . .

EXPOSE 3000
CMD [ "node", "server.js" ]
